# coding: utf-8

# flake8: noqa
"""
    MTAA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from Orders.api_models.models.accommodation import Accommodation
from Orders.api_models.models.accommodation_rating import AccommodationRating
from Orders.api_models.models.auth_request import AuthRequest
from Orders.api_models.models.auth_response import AuthResponse
from Orders.api_models.models.auth_token import AuthToken
from Orders.api_models.models.body import Body
from Orders.api_models.models.filter import Filter
from Orders.api_models.models.id_value import IdValue
from Orders.api_models.models.location import Location
from Orders.api_models.models.order import Order
from Orders.api_models.models.rating import Rating
from Orders.api_models.models.rating_reply import RatingReply
from Orders.api_models.models.user import User
