# coding: utf-8

"""
    MTAA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Orders.api_models.configuration import Configuration


class AccommodationRating(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'average': 'float',
        'count': 'int',
        'ratings': 'list[Rating]'
    }

    attribute_map = {
        'average': 'average',
        'count': 'count',
        'ratings': 'ratings'
    }

    def __init__(self, average=None, count=None, ratings=None, local_vars_configuration=None):  # noqa: E501
        """AccommodationRating - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._average = None
        self._count = None
        self._ratings = None
        self.discriminator = None

        if average is not None:
            self.average = average
        if count is not None:
            self.count = count
        if ratings is not None:
            self.ratings = ratings

    @property
    def average(self):
        """Gets the average of this AccommodationRating.  # noqa: E501


        :return: The average of this AccommodationRating.  # noqa: E501
        :rtype: float
        """
        return self._average

    @average.setter
    def average(self, average):
        """Sets the average of this AccommodationRating.


        :param average: The average of this AccommodationRating.  # noqa: E501
        :type: float
        """

        self._average = average

    @property
    def count(self):
        """Gets the count of this AccommodationRating.  # noqa: E501


        :return: The count of this AccommodationRating.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this AccommodationRating.


        :param count: The count of this AccommodationRating.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def ratings(self):
        """Gets the ratings of this AccommodationRating.  # noqa: E501


        :return: The ratings of this AccommodationRating.  # noqa: E501
        :rtype: list[Rating]
        """
        return self._ratings

    @ratings.setter
    def ratings(self, ratings):
        """Sets the ratings of this AccommodationRating.


        :param ratings: The ratings of this AccommodationRating.  # noqa: E501
        :type: list[Rating]
        """

        self._ratings = ratings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccommodationRating):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AccommodationRating):
            return True

        return self.to_dict() != other.to_dict()
