# coding: utf-8

"""
    MTAA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Orders.api_models.configuration import Configuration


class Accommodation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'title': 'str',
        'description': 'str',
        'images': 'list[str]',
        'location': 'Location',
        'occupant_count': 'int',
        'rating': 'AccommodationRating'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'description': 'description',
        'images': 'images',
        'location': 'location',
        'occupant_count': 'occupant_count',
        'rating': 'rating'
    }

    def __init__(self, id=None, title=None, description=None, images=None, location=None, occupant_count=None, rating=None, local_vars_configuration=None):  # noqa: E501
        """Accommodation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._title = None
        self._description = None
        self._images = None
        self._location = None
        self._occupant_count = None
        self._rating = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        if images is not None:
            self.images = images
        if location is not None:
            self.location = location
        if occupant_count is not None:
            self.occupant_count = occupant_count
        if rating is not None:
            self.rating = rating

    @property
    def id(self):
        """Gets the id of this Accommodation.  # noqa: E501


        :return: The id of this Accommodation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Accommodation.


        :param id: The id of this Accommodation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this Accommodation.  # noqa: E501


        :return: The title of this Accommodation.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Accommodation.


        :param title: The title of this Accommodation.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this Accommodation.  # noqa: E501


        :return: The description of this Accommodation.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Accommodation.


        :param description: The description of this Accommodation.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def images(self):
        """Gets the images of this Accommodation.  # noqa: E501


        :return: The images of this Accommodation.  # noqa: E501
        :rtype: list[str]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this Accommodation.


        :param images: The images of this Accommodation.  # noqa: E501
        :type: list[str]
        """

        self._images = images

    @property
    def location(self):
        """Gets the location of this Accommodation.  # noqa: E501


        :return: The location of this Accommodation.  # noqa: E501
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Accommodation.


        :param location: The location of this Accommodation.  # noqa: E501
        :type: Location
        """

        self._location = location

    @property
    def occupant_count(self):
        """Gets the occupant_count of this Accommodation.  # noqa: E501


        :return: The occupant_count of this Accommodation.  # noqa: E501
        :rtype: int
        """
        return self._occupant_count

    @occupant_count.setter
    def occupant_count(self, occupant_count):
        """Sets the occupant_count of this Accommodation.


        :param occupant_count: The occupant_count of this Accommodation.  # noqa: E501
        :type: int
        """

        self._occupant_count = occupant_count

    @property
    def rating(self):
        """Gets the rating of this Accommodation.  # noqa: E501


        :return: The rating of this Accommodation.  # noqa: E501
        :rtype: AccommodationRating
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """Sets the rating of this Accommodation.


        :param rating: The rating of this Accommodation.  # noqa: E501
        :type: AccommodationRating
        """

        self._rating = rating

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Accommodation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Accommodation):
            return True

        return self.to_dict() != other.to_dict()
