# coding: utf-8

"""
    MTAA API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Orders.api_models.configuration import Configuration


class Body(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'accommodation': 'str',
        'booking': 'str'
    }

    attribute_map = {
        'accommodation': 'accommodation',
        'booking': 'booking'
    }

    def __init__(self, accommodation=None, booking=None, local_vars_configuration=None):  # noqa: E501
        """Body - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._accommodation = None
        self._booking = None
        self.discriminator = None

        if accommodation is not None:
            self.accommodation = accommodation
        if booking is not None:
            self.booking = booking

    @property
    def accommodation(self):
        """Gets the accommodation of this Body.  # noqa: E501


        :return: The accommodation of this Body.  # noqa: E501
        :rtype: str
        """
        return self._accommodation

    @accommodation.setter
    def accommodation(self, accommodation):
        """Sets the accommodation of this Body.


        :param accommodation: The accommodation of this Body.  # noqa: E501
        :type: str
        """

        self._accommodation = accommodation

    @property
    def booking(self):
        """Gets the booking of this Body.  # noqa: E501


        :return: The booking of this Body.  # noqa: E501
        :rtype: str
        """
        return self._booking

    @booking.setter
    def booking(self, booking):
        """Sets the booking of this Body.


        :param booking: The booking of this Body.  # noqa: E501
        :type: str
        """

        self._booking = booking

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Body):
            return True

        return self.to_dict() != other.to_dict()
